[BE-8] Hero Section Responsive
archis-academy/july-bebka-beginner-coral-buy-3 pull request #17
Opened 2024-08-26 00:10 UTC by HilalSeyhan

2024-08-26 17:12 UTC, MehmetSunguralp commented
![image](https://github.com/user-attachments/assets/3c2565c6-dc18-4280-994d-216bb99c1698)

Buradaki taşmayı çözer misin?

2024-08-28 21:15 UTC, HilalSeyhan commented
![image](https://github.com/user-attachments/assets/310a11a6-44be-41cf-b705-48ccca43c209)

2024-08-28 21:20 UTC, HilalSeyhan commented
![image](https://github.com/user-attachments/assets/ffbe85c5-4b18-4a7a-b611-b16f820997d3)

düzelttim hocam

2024-08-29 09:49 UTC, MehmetSunguralp requested changes
merge conflict çözer misin?

2024-08-29 15:48 UTC, MehmetSunguralp approved these changes

2024-08-29 15:49 UTC, merged