[BE-11]-Product View Template Responsiveness
archis-academy/july-bebka-beginner-coral-buy-3 pull request #8
Opened 2024-08-10 18:15 UTC by berfinesenn

2024-08-15 15:13 UTC, MehmetSunguralp requested changes

2024-08-15 15:13 UTC, MehmetSunguralp commented on styles/style.css
Daha çok media query eklemelisin

2024-08-17 15:09 UTC, MehmetSunguralp commented
Merge conflict de çözmen gerekiyor

2024-08-24 18:53 UTC, MehmetSunguralp requested changes
![image](https://github.com/user-attachments/assets/0cd54fe3-8e01-4e7f-8c12-95a5a4bd89b9)
355 pixelden sonra aşırı küçülüyor. font-size'lar için 10 veya 12 pixelden daha küçük değer kullanmamalısın çünkü okunabilirlik düşüyor. Resimleri de o kadar küçültmene gerek yok,. Yan yana iki ürün gelecek şekilde tekrar güncelle

2024-08-24 22:55 UTC, berfinesenn commented
![Screenshot 2024-08-25 014703](https://github.com/user-attachments/assets/59d6ef4f-fa9e-4f45-a2bc-aaa35d650134)
![Screenshot 2024-08-25 013217](https://github.com/user-attachments/assets/66063563-e7cd-41d2-a0ea-80e81d5f0296)
hocam son şekliyle böyle oldu 332px den aşağısına küçültünce tek resme düşüyor. İkili yapmak istedim ama bu seferde ürün etiketi iç içine giriyor yazılar. Font için 10px den aşa verme dediğiniz içinde bu şekilde bırakıp pushluyorum .

2024-08-26 19:22 UTC, berfinesenn commented
İstediğiniz gibi 630px de product-details ta width değeri yok , bottom-product ta width değeri 140px olarak yazdım.

2024-08-27 13:43 UTC, MehmetSunguralp approved these changes

2024-08-27 13:43 UTC, merged